qpOASES: SymmetricMatrix Class Reference
SymmetricMatrix Class Reference abstract
Abstract base class for interfacing matrix-vector operations tailored to symmetric matrices.
#include <Matrices.hpp>
Public Member Functions
SymmetricMatrix ()
virtual ~SymmetricMatrix ()
virtual SymmetricMatrix * duplicateSym () const =0
virtual returnValue bilinear (const Indexlist *const icols, int_t xN, const real_t *x, int_t xLD, real_t *y, int_t yLD) const =0
virtual void free ()=0
virtual Matrix * duplicate () const =0
virtual real_t diag (int_t i) const =0
virtual BooleanType isDiag () const =0
virtual real_t getNorm (int_t type=2) const =0
virtual real_t getRowNorm (int_t rNum, int_t type=2) const =0
virtual returnValue getRow (int_t rNum, const Indexlist *const icols, real_t alpha, real_t *row) const =0
virtual returnValue getCol (int_t cNum, const Indexlist *const irows, real_t alpha, real_t *col) const =0
virtual returnValue getSparseSubmatrix (const Indexlist *const irows, const Indexlist *const icols, int_t rowoffset, int_t coloffset, int_t &numNonzeros, int_t *irn, int_t *jcn, real_t *avals, BooleanType only_lower_triangular=BT_FALSE) const
virtual returnValue getSparseSubmatrix (const Indexlist *const irows, int_t idx_icol, int_t rowoffset, int_t coloffset, int_t &numNonzeros, int_t *irn, int_t *jcn, real_t *avals, BooleanType only_lower_triangular=BT_FALSE) const
virtual returnValue getSparseSubmatrix (int_t idx_row, const Indexlist *const icols, int_t rowoffset, int_t coloffset, int_t &numNonzeros, int_t *irn, int_t *jcn, real_t *avals, BooleanType only_lower_triangular=BT_FALSE) const
virtual returnValue getSparseSubmatrix (int_t irowsLength, const int_t *const irowsNumber, int_t icolsLength, const int_t *const icolsNumber, int_t rowoffset, int_t coloffset, int_t &numNonzeros, int_t *irn, int_t *jcn, real_t *avals, BooleanType only_lower_triangular=BT_FALSE) const =0
virtual returnValue times (int_t xN, real_t alpha, const real_t *x, int_t xLD, real_t beta, real_t *y, int_t yLD) const =0
virtual returnValue times (const Indexlist *const irows, const Indexlist *const icols, int_t xN, real_t alpha, const real_t *x, int_t xLD, real_t beta, real_t *y, int_t yLD, BooleanType yCompr=BT_TRUE) const =0
virtual returnValue transTimes (int_t xN, real_t alpha, const real_t *x, int_t xLD, real_t beta, real_t *y, int_t yLD) const =0
virtual returnValue transTimes (const Indexlist *const irows, const Indexlist *const icols, int_t xN, real_t alpha, const real_t *x, int_t xLD, real_t beta, real_t *y, int_t yLD) const =0
virtual returnValue addToDiag (real_t alpha)=0
virtual real_t * full () const =0
virtual returnValue print (const char *name=0) const =0
virtual returnValue writeToFile (FILE *output_file, const char *prefix) const =0
BooleanType needToFreeMemory () const
void doFreeMemory ()
void doNotFreeMemory ()
Protected Attributes
BooleanType freeMemory
Detailed Description
Abstract base class for symmetric matrices. Extends Matrix interface with bilinear form evaluation.
Author
Andreas Potschka, Christian Kirches, Hans Joachim Ferreau
Version
3.2
Date
2011-2015
Constructor & Destructor Documentation
SymmetricMatrix::SymmetricMatrix () inline
Default constructor.
virtual SymmetricMatrix::~SymmetricMatrix () inline virtual
Destructor.
References real_t.
Member Function Documentation
virtual returnValue Matrix::addToDiag (real_t alpha) pure virtual inherited
Adds given offset to diagonal of matrix.
Returns
SUCCESSFUL_RETURN
RET_NO_DIAGONAL_AVAILABLE
Parameters
alpha Diagonal offset.
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
Referenced by DenseMatrix::DenseMatrix(), QProblemB::regulariseHessian(), and Matrix::~Matrix().
virtual returnValue SymmetricMatrix::bilinear (const Indexlist *const icols, int_t xN, const real_t * x, int_t xLD, real_t * y, int_t yLD) const pure virtual
Compute bilinear form y = x'*H*x using submatrix given by index list.
Returns
SUCCESSFUL_RETURN
Parameters
icols Index list specifying columns of x.
xN Number of vectors to multiply.
x Input vector to be multiplied (uncompressed).
xLD Leading dimension of input x.
y Output vector of results (compressed).
yLD Leading dimension of output y.
Implemented in SymSparseMat, and SymDenseMat.
Referenced by QProblem::computeProjectedCholesky().
virtual real_t Matrix::diag (int_t i) const pure virtual inherited
Returns i-th diagonal entry.
Returns
i-th diagonal entry
Parameters
i Index.
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
Referenced by DenseMatrix::DenseMatrix(), QProblemB::determineHessianType(), QProblem::removeBound(), QProblemB::removeBound(), and Matrix::~Matrix().
void Matrix::doFreeMemory () inline inherited
Enables de-allocation of internal memory.
References BT_TRUE, and Matrix::freeMemory.
Referenced by QProblemB::createDiagSparseMat(), DenseMatrix::duplicate(), SparseMatrix::duplicate(), SparseMatrixRow::duplicate(), SymDenseMat::duplicateSym(), SymSparseMat::duplicateSym(), QProblemB::setupQPdataFromFile(), QProblem::setupQPdataFromFile(), solveOqpBenchmark(), SparseMatrix::SparseMatrix(), and SparseMatrixRow::SparseMatrixRow().
void Matrix::doNotFreeMemory () inline inherited
Disables de-allocation of internal memory.
Referenced by SparseMatrix::free(), SparseMatrixRow::free(), Matrix::Matrix(), SparseMatrix::SparseMatrix(), and SparseMatrixRow::SparseMatrixRow().
virtual Matrix* Matrix::duplicate () const pure virtual inherited
Returns a deep-copy of the Matrix object.
Returns
Deep-copy of Matrix object
Implemented in SymSparseMat, SparseMatrixRow, SparseMatrix, SymDenseMat, and DenseMatrix.
Referenced by QProblem::copy(), DenseMatrix::DenseMatrix(), Matrix::~Matrix(), SymDenseMat::~SymDenseMat(), and SymSparseMat::~SymSparseMat().
virtual SymmetricMatrix* SymmetricMatrix::duplicateSym () const pure virtual
Returns a deep-copy of the SymmetricMatrix object.
Returns
Deep-copy of SymmetricMatrix object
Implemented in SymSparseMat, and SymDenseMat.
Referenced by QProblemB::copy().
virtual void Matrix::free () pure virtual inherited
Frees all internal memory.
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
Referenced by DenseMatrix::DenseMatrix(), DenseMatrix::~DenseMatrix(), and Matrix::~Matrix().
virtual real_t* Matrix::full () const pure virtual inherited
Allocates and creates dense matrix array in row major format.
Note: Calling function has to free allocated memory!
Returns
Pointer to matrix array.
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
Referenced by DenseMatrix::DenseMatrix(), SolutionAnalysis::getKktViolation(), QProblem::writeQpDataIntoMatFile(), and Matrix::~Matrix().
virtual returnValue Matrix::getCol (int_t cNum, const Indexlist *const irows, real_t alpha, real_t * col) const pure virtual inherited
Retrieve indexed entries of matrix column multiplied by alpha.
Returns
SUCCESSFUL_RETURN
Parameters
cNum Column number.
irows Index list specifying rows.
alpha Scalar factor.
col Output column vector.
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
Referenced by QProblemB::computeCholesky(), QProblem::computeProjectedCholesky(), DenseMatrix::DenseMatrix(), QProblem::removeBound(), and Matrix::~Matrix().
virtual real_t Matrix::getNorm (int_t type = 2) const pure virtual inherited
Get the N-norm of the matrix
Returns
N-norm of the matrix
Parameters
type Norm type, 1: one-norm, 2: Euclidean norm.
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
Referenced by DenseMatrix::DenseMatrix(), DenseMatrix::getNorm(), DenseMatrix::getRowNorm(), QProblemB::regulariseHessian(), and Matrix::~Matrix().
virtual returnValue Matrix::getRow (int_t rNum, const Indexlist *const icols, real_t alpha, real_t * row) const pure virtual inherited
Retrieve indexed entries of matrix row multiplied by alpha.
Returns
SUCCESSFUL_RETURN
Parameters
rNum Row number.
icols Index list specifying columns.
alpha Scalar factor.
row Output row vector.
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
Referenced by QProblem::addConstraint(), QProblem::addConstraint_checkLI(), SQProblemSchur::addConstraint_checkLISchur(), QProblem::addConstraint_ensureLI(), DenseMatrix::DenseMatrix(), QProblemB::removeBound(), and Matrix::~Matrix().
virtual real_t Matrix::getRowNorm (int_t rNum, int_t type = 2) const pure virtual inherited
Get the N-norm of a row
Returns
N-norm of row rNum
Parameters
rNum Row number.
type Norm type, 1: one-norm, 2: Euclidean norm.
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
Referenced by DenseMatrix::DenseMatrix(), QProblem::setA(), and Matrix::~Matrix().
BEGIN_NAMESPACE_QPOASES returnValue Matrix::getSparseSubmatrix (const Indexlist *const irows, const Indexlist *const icols, int_t rowoffset, int_t coloffset, int_t & numNonzeros, int_t * irn, int_t * jcn, real_t * avals, BooleanType only_lower_triangular = BT_FALSE) const virtual inherited
Retrieve entries of submatrix in Harwell-Boeing sparse format. If irn, jcn, and avals are null, this only counts the number of nonzeros. Otherwise, numNonzeros containts the size of irn, jcn, and avals on entry, and the written number of entries on return.
Returns
SUCCESSFUL_RETURN
Parameters
irows Index list specifying rows.
icols Index list specifying columns.
rowoffset Offset for row entries.
coloffset Offset for row entries.
numNonzeros Number of nonzeros in submatrix.
irn Row position of entries (as position in irows) plus rowoffset.
jcn Column position of entries (as position in irows) plus coloffset.
avals Numerical values of the entries.
only_lower_triangular if true, only the lower triangular portion is returned. This can only be true for symmetric matrices and if irows==jcols.
References Indexlist::getLength(), and Indexlist::getNumberArray().
Referenced by SQProblemSchur::addConstraint(), DenseMatrix::DenseMatrix(), Matrix::getSparseSubmatrix(), SQProblemSchur::removeBound(), SQProblemSchur::resetSchurComplement(), and Matrix::~Matrix().
returnValue Matrix::getSparseSubmatrix (const Indexlist *const irows, int_t idx_icol, int_t rowoffset, int_t coloffset, int_t & numNonzeros, int_t * irn, int_t * jcn, real_t * avals, BooleanType only_lower_triangular = BT_FALSE) const virtual inherited
Retrieve entries of submatrix in Harwell-Boeing sparse format. If irn, jcn, and avals are null, this only counts the number of nonzeros. Otherwise, numNonzeros containts the size of irn, jcn, and avals on entry, and the written number of entries on return. This version retrieves one column.
Returns
SUCCESSFUL_RETURN
Parameters
irows Index list specifying rows.
idx_icol Index list specifying columns.
rowoffset Offset for row entries.
coloffset Offset for row entries.
numNonzeros Number of nonzeros in submatrix.
irn Row position of entries (as position in irows) plus rowoffset.
jcn Column position of entries (as position in irows) plus coloffset.
avals Numerical values of the entries.
only_lower_triangular if true, only the lower triangular portion is returned. This can only be true for symmetric matrices and if irows==jcols.
References Indexlist::getLength(), Indexlist::getNumberArray(), and Matrix::getSparseSubmatrix().
returnValue Matrix::getSparseSubmatrix (int_t idx_row, const Indexlist *const icols, int_t rowoffset, int_t coloffset, int_t & numNonzeros, int_t * irn, int_t * jcn, real_t * avals, BooleanType only_lower_triangular = BT_FALSE) const virtual inherited
Retrieve entries of submatrix in Harwell-Boeing sparse format. If irn, jcn, and avals are null, this only counts the number of nonzeros. Otherwise, numNonzeros containts the size of irn, jcn, and avals on entry, and the written number of entries on return. This version retrieves one row.
Returns
SUCCESSFUL_RETURN
Parameters
idx_row Row number.
icols Index list specifying columns.
rowoffset Offset for row entries.
coloffset Offset for row entries.
numNonzeros Number of nonzeros in submatrix.
irn Row position of entries (as position in irows) plus rowoffset.
jcn Column position of entries (as position in irows) plus coloffset.
avals Numerical values of the entries.
only_lower_triangular if true, only the lower triangular portion is returned. This can only be true for symmetric matrices and if irows==jcols.
References Indexlist::getLength(), Indexlist::getNumberArray(), and Matrix::getSparseSubmatrix().
virtual returnValue Matrix::getSparseSubmatrix (int_t irowsLength, const int_t *const irowsNumber, int_t icolsLength, const int_t *const icolsNumber, int_t rowoffset, int_t coloffset, int_t & numNonzeros, int_t * irn, int_t * jcn, real_t * avals, BooleanType only_lower_triangular = BT_FALSE) const pure virtual inherited
Retrieve entries of submatrix in Harwell-Boeing sparse format. If irn, jcn, and avals are null, this only counts the number of nonzeros. Otherwise, numNonzeros containts the size of irn, jcn, and avals on entry, and the written number of entries on return.
Returns
SUCCESSFUL_RETURN
Parameters
irowsLength Number of rows.
irowsNumber Array with row numbers.
icolsLength Number of columns.
icolsNumber Array with column numbers.
rowoffset Offset for row entries.
coloffset Offset for row entries.
numNonzeros Number of nonzeros in submatrix.
irn Row position of entries (as position in irows) plus rowoffset.
jcn Column position of entries (as position in irows) plus coloffset.
avals Numerical values of the entries.
only_lower_triangular if true, only the lower triangular portion is returned. This can only be true for symmetric matrices and if irows==jcols.
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
virtual BooleanType Matrix::isDiag () const pure virtual inherited
Checks whether matrix is square and diagonal.
Returns
BT_TRUE iff matrix is square and diagonal;
BT_FALSE otherwise.
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
Referenced by DenseMatrix::DenseMatrix(), QProblemB::determineHessianType(), and Matrix::~Matrix().
BooleanType Matrix::needToFreeMemory () const inline inherited
Returns whether internal memory needs to be de-allocated.
Returns
BT_TRUE iff internal memory needs to be de-allocated,
BT_FALSE otherwise
References Matrix::freeMemory.
Referenced by DenseMatrix::duplicate(), SymDenseMat::duplicateSym(), DenseMatrix::~DenseMatrix(), SparseMatrix::~SparseMatrix(), and SparseMatrixRow::~SparseMatrixRow().
virtual returnValue Matrix::print (const char * name = 0) const pure virtual inherited
Prints matrix to screen.
Returns
SUCCESSFUL_RETURN
Parameters
name Name of matrix.
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
Referenced by DenseMatrix::DenseMatrix(), DenseMatrix::print(), and Matrix::~Matrix().
virtual returnValue Matrix::times (int_t xN, real_t alpha, const real_t * x, int_t xLD, real_t beta, real_t * y, int_t yLD) const pure virtual inherited
Evaluate Y=alpha*A*X + beta*Y.
Returns
SUCCESSFUL_RETURN
Parameters
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
Referenced by SQProblemSchur::backsolveSchurQR(), DenseMatrix::DenseMatrix(), QProblem::determineStepDirection(), QProblemB::determineStepDirection(), QProblem::ensureNonzeroCurvature(), QProblemB::getObjVal(), QProblem::performStep(), QProblem::printIteration(), QProblemB::printIteration(), QProblem::removeBound(), QProblem::removeConstraint(), QProblem::setA(), QProblem::setupAuxiliaryQP(), QProblem::setupAuxiliaryQPgradient(), QProblemB::setupAuxiliaryQPgradient(), QProblem::setupAuxiliaryQPsolution(), and Matrix::~Matrix().
virtual returnValue Matrix::times (const Indexlist *const irows, const Indexlist *const icols, int_t xN, real_t alpha, const real_t * x, int_t xLD, real_t beta, real_t * y, int_t yLD, BooleanType yCompr = BT_TRUE) const pure virtual inherited
Evaluate matrix vector product with submatrix given by Indexlist.
Returns
SUCCESSFUL_RETURN
Parameters
irows Index list specifying rows.
icols Index list specifying columns.
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
yCompr Compressed storage for y.
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
virtual returnValue Matrix::transTimes (int_t xN, real_t alpha, const real_t * x, int_t xLD, real_t beta, real_t * y, int_t yLD) const pure virtual inherited
Evaluate Y=alpha*A'*X + beta*Y.
Returns
SUCCESSFUL_RETURN
Parameters
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
Referenced by QProblem::addBound_ensureLI(), QProblem::addConstraint_ensureLI(), SQProblemSchur::backsolveSchurQR(), DenseMatrix::DenseMatrix(), QProblem::determineStepDirection(), QProblem::printIteration(), QProblem::setupAuxiliaryQPgradient(), and Matrix::~Matrix().
virtual returnValue Matrix::transTimes (const Indexlist *const irows, const Indexlist *const icols, int_t xN, real_t alpha, const real_t * x, int_t xLD, real_t beta, real_t * y, int_t yLD) const pure virtual inherited
Evaluate matrix transpose vector product.
Returns
SUCCESSFUL_RETURN
Parameters
irows Index list specifying rows.
icols Index list specifying columns.
xN Number of vectors to multiply.
alpha Scalar factor for matrix vector product.
x Input vector to be multiplied.
xLD Leading dimension of input x.
beta Scalar factor for y.
y Output vector of results.
yLD Leading dimension of output y.
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
virtual returnValue Matrix::writeToFile (FILE * output_file, const char * prefix) const pure virtual inherited
Write matrix to file.
Returns
SUCCESSFUL_RETURN
Implemented in SparseMatrixRow, SparseMatrix, and DenseMatrix.
Referenced by DenseMatrix::DenseMatrix(), QProblem::setupQPdata(), and Matrix::~Matrix().
Member Data Documentation
BooleanType Matrix::freeMemory protected inherited
Indicating whether internal memory needs to be de-allocated.
Referenced by Matrix::doFreeMemory(), and Matrix::needToFreeMemory().
The documentation for this class was generated from the following file:
include/qpOASES/Matrices.hpp