qpOASES: SparseSolver Class Reference
SparseSolver Class Reference abstract
Base class for linear solvers that are used in a Schur-complement implementation in qpOASES.
#include <SparseSolver.hpp>
Public Member Functions
SparseSolver ()
SparseSolver (const SparseSolver &rhs)
virtual ~SparseSolver ()
virtual SparseSolver & operator= (const SparseSolver &rhs)
virtual returnValue setMatrixData (int_t dim, int_t numNonzeros, const int_t *const airn, const int_t *const acjn, const real_t *const avals)=0
virtual returnValue factorize ()=0
virtual returnValue solve (int_t dim, const real_t *const rhs, real_t *const sol)=0
virtual returnValue reset ()
virtual int_t getNegativeEigenvalues ()
virtual int_t getRank ()
virtual returnValue getZeroPivots (int_t *&zeroPivots)
Protected Member Functions
returnValue clear ()
returnValue copy (const SparseSolver &rhs)
Detailed Description
Author
Andreas Waechter, Dennis Janka
Version
3.2
Date
2012-2015
Constructor & Destructor Documentation
BEGIN_NAMESPACE_QPOASES SparseSolver::SparseSolver ()
Default constructor.
Referenced by copy().
SparseSolver::SparseSolver (const SparseSolver & rhs)
Copy constructor (deep copy).
Parameters
rhs Rhs object.
References copy().
SparseSolver::~SparseSolver () virtual
Destructor.
References clear().
Member Function Documentation
returnValue SparseSolver::clear () protected
Frees all allocated memory.
Returns
SUCCESSFUL_RETURN
References SUCCESSFUL_RETURN.
Referenced by copy(), operator=(), and ~SparseSolver().
returnValue SparseSolver::copy (const SparseSolver & rhs) protected
Copies all members from given rhs object.
Returns
SUCCESSFUL_RETURN
Parameters
rhs Rhs object.
References BT_FALSE, clear(), END_NAMESPACE_QPOASES, getGlobalMessageHandler(), getMax(), isZero(), operator=(), real_t, reset(), RET_INVALID_ARGUMENTS, RET_KKT_MATRIX_SINGULAR, RET_MATRIX_FACTORISATION_FAILED, RET_NO_SPARSE_SOLVER, RET_RESET_FAILED, SparseSolver(), SUCCESSFUL_RETURN, and THROWERROR.
Referenced by operator=(), and SparseSolver().
virtual returnValue SparseSolver::factorize () pure virtual
Compute factorization of current matrix. This method must be called before solve.
Referenced by SQProblemSchur::resetSchurComplement().
int_t SparseSolver::getNegativeEigenvalues () virtual
Return the number of negative eigenvalues.
Referenced by SolutionAnalysis::checkCurvatureOnStronglyActiveConstraints(), SQProblemSchur::correctInertia(), SQProblemSchur::removeBound(), SQProblemSchur::removeConstraint(), SQProblemSchur::resetSchurComplement(), SQProblemSchur::setupAuxiliaryQP(), and SQProblemSchur::setupAuxiliaryWorkingSet().
int_t SparseSolver::getRank () virtual
Return the rank after a factorization
Referenced by SQProblemSchur::repairSingularWorkingSet().
returnValue SparseSolver::getZeroPivots (int_t *& zeroPivots) virtual
Returns the zero pivots in case the matrix is rank deficient
References SUCCESSFUL_RETURN.
Referenced by SQProblemSchur::repairSingularWorkingSet().
SparseSolver & SparseSolver::operator= (const SparseSolver & rhs) virtual
Assignment operator (deep copy).
Parameters
rhs Rhs object.
References clear(), and copy().
Referenced by copy().
returnValue SparseSolver::reset () virtual
Clears all data structures.
References SUCCESSFUL_RETURN.
Referenced by copy(), SQProblemSchur::reset(), and SQProblemSchur::resetSchurComplement().
virtual returnValue SparseSolver::setMatrixData (int_t dim, int_t numNonzeros, const int_t *const airn, const int_t *const acjn, const real_t *const avals) pure virtual
Set new matrix data. The matrix is to be provided in the Harwell-Boeing format. Only the lower triangular part should be set.
Parameters
dim Dimension of the linear system.
numNonzeros Number of nonzeros in the matrix.
airn Row indices for each matrix entry.
acjn Column indices for each matrix entry.
avals Values for each matrix entry.
Referenced by SQProblemSchur::resetSchurComplement().
virtual returnValue SparseSolver::solve (int_t dim, const real_t *const rhs, real_t *const sol) pure virtual
Solve linear system with most recently set matrix data.
Parameters
dim Dimension of the linear system.
rhs Values for the right hand side.
sol Solution of the linear system.
Referenced by SQProblemSchur::addToSchurComplement(), SQProblemSchur::backsolveSchurQR(), and SQProblemSchur::determineStepDirection2().
The documentation for this class was generated from the following files:
include/qpOASES/SparseSolver.hpp
src/SparseSolver.cpp