qpOASES: examples/example2.cpp File Reference
example2.cpp File Reference
#include <qpOASES.hpp>
Functions
int main ()
Detailed Description
Author
Hans Joachim Ferreau (thanks to Boris Houska)
Version
3.2
Date
2008-2015
Very simple example for testing qpOASES in combination with the SolutionAnalysis class.
Function Documentation
int main ()
Example for qpOASES main function using the SolutionAnalysis class.
References SolutionAnalysis::getKktViolation(), SolutionAnalysis::getVarianceCovariance(), SQProblem::hotstart(), QProblem::init(), real_t, and USING_NAMESPACE_QPOASES.